"""Adds wants_email column to Student

Revision ID: 3b2ff38c1aa6
Revises: a9dff97230d6
Create Date: 2021-01-06 17:02:03.096054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2ff38c1aa6'
down_revision = 'a9dff97230d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('wants_email', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'wants_email')
    # ### end Alembic commands ###
