"""Drops want_email column from student

Revision ID: 96aeb5bb2a82
Revises: 3b2ff38c1aa6
Create Date: 2021-01-06 17:05:09.274784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96aeb5bb2a82'
down_revision = '3b2ff38c1aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'wants_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('wants_email', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
