"""Drops want_email column from student

Revision ID: a9dff97230d6
Revises: 36f061da40c4
Create Date: 2021-01-06 16:59:55.955482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9dff97230d6'
down_revision = '36f061da40c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'wants_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('wants_email', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
