"""empty message

Revision ID: c1e668a27bfd
Revises: 
Create Date: 2021-01-04 20:45:25.799137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e668a27bfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_name')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('deadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.Integer(), nullable=False),
    sa.Column('brief_desc', sa.String(length=100), nullable=False),
    sa.Column('details', sa.String(length=750), nullable=True),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('submit_date', sa.Date(), nullable=False),
    sa.Column('submit_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['course'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signup')
    op.drop_table('deadline')
    op.drop_table('student')
    op.drop_table('course')
    # ### end Alembic commands ###
